/* Generated by Silver Content Studio. Public content only. */
window.SILVER_DATA = {
  "profile": {
    "name": "周瑜鸿",
    "availability": "SYSTEM ONLINE · HANGZHOU, CN",
    "role": "AI GAME PLANNER / SYSTEM DESIGNER",
    "statement": "我设计由 AI 驱动的游戏机制，也在设计自己的成长系统。",
    "email": "19858810407@139.com",
    "updatedAt": "2026.07.31",
    "chapter": {
      "code": "CHAPTER 04 / CAREER ENTRY",
      "title": "腾讯副本",
      "summary": "从学生原型开发转向工业化游戏生产，在真实协作中建立玩法策划与 AI 系统能力。",
      "meta": [
        [
          "LOCATION",
          "杭州"
        ],
        [
          "ROLE",
          "AI 游戏策划"
        ],
        [
          "STATUS",
          "探索中"
        ]
      ]
    },
    "quest": {
      "title": "完成职业能力迁移",
      "progress": 68
    },
    "metrics": [
      {
        "label": "ACTIVE PROJECTS",
        "value": "02",
        "note": "BUILDING"
      },
      {
        "label": "RELEASED PROTOTYPES",
        "value": "04",
        "note": "VERIFIED"
      },
      {
        "label": "CURRENT VERSION",
        "value": "21.4",
        "note": "STABLE"
      },
      {
        "label": "NEXT MILESTONE",
        "value": "AI PRODUCT",
        "note": "LOCKED"
      }
    ]
  },
  "experience": [
    {
      "period": "2026.05 — 2026.11",
      "company": "腾娱互动（腾讯子公司）",
      "role": "AI 游戏策划实习生",
      "status": "实习中",
      "summary": "参与 AI 小游戏的策划与制作，把模型能力转化为可以运行、验证和迭代的游戏流程。",
      "highlights": [
        "参与 AI 小游戏从玩法构想到原型制作的工作流程",
        "完成游戏角色一键 AI 换肤流程的策划与制作",
        "参与游戏测试提出并复现bug并讨论解决方案"
      ]
    }
  ],
  "education": {
    "school": "温州大学",
    "major": "人工智能",
    "degree": "本科在读",
    "direction": "AI 玩法策划 / 游戏系统设计"
  },
  "skillGroups": [
    {
      "label": "GAME DEVELOPMENT",
      "value": "Godot 4.x / GDScript / Dialogue Manager"
    },
    {
      "label": "AI SYSTEMS",
      "value": "Prompt 工程 / RAG / DeepSeek API / 动态状态系统"
    },
    {
      "label": "PROGRAMMING",
      "value": "Python / PyTorch / OpenCV / SQL / Git"
    },
    {
      "label": "DESIGN",
      "value": "GDD / 核心循环 / 数值框架 / 多分支叙事"
    }
  ],
  "honors": [
    "浙江省挑战杯银奖",
    "浙江省大创银奖、铜奖",
    "校级 AIGC 一等奖",
    "亚太杯数学建模 F 奖",
    "温州大学二等奖学金"
  ],
  "lab": [
    {
      "id": "LAB—02",
      "title": "LeNet-5 手写数字识别",
      "status": "COMPLETED",
      "summary": "复刻经典 CNN，并通过 Flask 与 Canvas 做成可交互的推理和特征可视化应用。",
      "question": "如何把模型训练、推理接口和浏览器交互连成完整链路？",
      "stack": [
        "PyTorch",
        "Flask",
        "HTML5 Canvas",
        "MNIST"
      ]
    },
    {
      "id": "LAB—03",
      "title": "车牌识别系统",
      "status": "COMPLETED",
      "summary": "实现图像预处理、车牌定位、字符分割与 SVM 识别流程，支持蓝、黄、绿车牌。",
      "question": "传统视觉方法如何在复杂背景中稳定完成字符识别？",
      "stack": [
        "OpenCV",
        "HOG",
        "SVM",
        "Python"
      ]
    },
    {
      "id": "LAB—04",
      "title": "电子日记系统",
      "status": "ARCHITECTURE",
      "summary": "面向日记管理、分享、好友关系和消息中心的 Web 系统架构设计。",
      "question": "如何组织带认证、社交关系与实时消息的完整 Web 应用？",
      "stack": [
        "Vue 3",
        "Spring Boot",
        "MySQL",
        "Redis"
      ]
    }
  ],
  "projects": [
    {
      "id": "OBS–P01",
      "slug": "interrogation-room-0",
      "category": "game",
      "status": "开发中",
      "title": "0号审讯室",
      "english": "Interrogation Room #0",
      "summary": "心理博弈审讯模拟。玩家通过证物与对话策略，在嫌疑人的心理状态变化中寻找突破口。",
      "problem": "传统对话树很容易退化成寻找正确选项。我希望审讯不是背答案，而是观察心理变化、组合证物并承担施压策略的后果。",
      "system": "用 mental health、stress level 和 suspicion 构成三维心理状态；证物标签与对话行为持续修改状态，再由状态决定角色反馈和可用策略。",
      "outcome": "核心审讯循环已经可以运行，下一阶段将补充完整案件内容、失败反馈与更清晰的心理状态表现。",
      "role": "玩法策划 / 独立开发",
      "evidence": [
        "三维心理状态引擎",
        "证物标签影响对话树",
        "Godot 4.5 / GDScript"
      ],
      "demoVideo": "assets/interrogation-room-0-demo.mp4",
      "index": "01"
    },
    {
      "id": "OBS–P02",
      "slug": "the-final-resonance",
      "category": "game",
      "status": "可运行 Demo",
      "title": "最终共鸣",
      "english": "The Final Resonance",
      "summary": "AI 驱动的心理惊悚叙事游戏。角色在动态 Prompt 控制下经历四阶段人格演变。",
      "problem": "生成式角色很容易只有随机对话，没有可感知的剧情推进。项目需要让模型变化成为叙事机制，而不是聊天装饰。",
      "system": "通过四阶段动态 Prompt、人格状态追踪和 RAG 镜像模仿控制角色演变，再将玩家行为映射到 16 种人格结局。",
      "outcome": "完成可运行 Demo 与主要系统验证，证明 AI 角色变化可以被组织成有方向的游戏体验。",
      "role": "系统设计 / 开发",
      "evidence": [
        "RAG 镜像模仿",
        "16 种 MBTI 结局",
        "约 3,000 行代码"
      ],
      "showcaseImage": "assets/the-final-resonance.jpg",
      "showcaseImageWebp": "assets/the-final-resonance.webp",
      "showcaseCrop": true,
      "showcaseCaption": "运行界面 / AI 对话与人格演变记录",
      "index": "02"
    },
    {
      "id": "OBS–P03",
      "slug": "cloud-mirage-express",
      "category": "game",
      "status": "暂停",
      "title": "云端列车",
      "english": "Cloud Mirage Express",
      "summary": "像素风调酒模拟经营，以收入、成本和税务构成三层经济循环。",
      "problem": "模拟经营需要让每次调酒、定价和采购都进入同一经济循环，同时保持内容可以被快速扩充。",
      "system": "以 CSV 管理配方与商品数据，结合 Godot Resource 承载运行状态，构成收入、成本和税务三层反馈。",
      "outcome": "完成主要经营框架后暂停开发，保留为数据驱动架构与协作开发的验证记录。",
      "role": "系统策划 / 协作开发",
      "evidence": [
        "CSV 数据驱动",
        "Resource 混合架构",
        "经济循环设计"
      ],
      "demoVideo": "assets/cloud-mirage-express-demo.mp4",
      "index": "03"
    },
    {
      "id": "OBS–P04",
      "slug": "casual-translation",
      "category": "ai",
      "status": "本地 Alpha",
      "title": "雅喵 IELTS Pet",
      "english": "IELTS Pet Learning Companion",
      "summary": "把每日英语练习转化为宠物成长的 Windows 桌面学习应用。",
      "problem": "雅思等长期学习目标反馈周期很长，用户很难从每天几分钟的练习中感受到进步。项目要解决的不是增加课程数量，而是让短期行动持续产生可见反馈，让用户愿意第二天继续学习。",
      "system": "以“短学习任务—即时反馈—宠物或空间成长—累计进步”为核心循环。React 与 TypeScript 构建交互层，Tauri v2 和 Rust 承载 Windows 桌面能力，SQLite 保存宠物、库存、生词与复习状态；DeepSeek 生成场景对话，规则系统控制交易、奖励和资产。",
      "outcome": "已完成透明置顶桌宠、像素房间、AI 场景对话、超市购买、背包与喂食、生词收藏和剪贴板取词等基础能力。当前技术原型约完成 60%，正在建设每日任务、学习奖励、成长可视化和口语反馈的本地 Alpha 核心闭环。",
      "role": "产品设计 / 系统设计 / 独立开发",
      "evidence": [
        "React 19 / TypeScript / Tauri v2",
        "Rust / SQLite / Zustand",
        "AI 场景对话与宠物成长闭环"
      ],
      "featuredOnHome": true,
      "index": "04",
      "date": "",
      "showcaseImage": "assets/uploads/1786780857448-760a13-2026-08-02-193900.png"
    },
    {
      "id": "OBS–P05",
      "slug": "first-game-making-experience",
      "category": "game",
      "status": "学习归档",
      "title": "游戏制作初体验",
      "english": "First Steps in Game Making",
      "date": "2025.09.11",
      "summary": "自学 Godot 引擎期间完成的入门练习，记录从理解引擎基础到第一次真正开始制作游戏的过程。",
      "problem": "如何把对游戏制作的兴趣转化为可以运行、可以操作的实际内容，而不只是停留在想法和策划文档中。",
      "system": "从 Godot 的场景、节点和脚本等基础概念开始，通过边学习边制作的方式建立对游戏运行结构与基础交互的理解。",
      "outcome": "完成早期可运行练习，建立了继续自学 Godot 与独立制作游戏的起点。",
      "role": "个人学习 / 独立练习",
      "evidence": [
        "Godot 引擎自学",
        "基础交互练习",
        "游戏制作入门"
      ],
      "demoVideo": "assets/first-game-making-experience-demo.mp4",
      "index": "05"
    }
  ],
  "fitnessPhotos": [
    {
      "day": 1,
      "date": "2026.8.14",
      "image": "assets/uploads/1787140529235-ecf7de-f4cee81ecf96389cb2f6242863945f66.jpg",
      "note": "初期"
    },
    {
      "day": 28,
      "date": "",
      "image": "",
      "note": ""
    },
    {
      "day": 56,
      "date": "",
      "image": "",
      "note": ""
    },
    {
      "day": 84,
      "date": "",
      "image": "",
      "note": ""
    }
  ],
  "capabilities": [
    {
      "code": "CAP–01",
      "title": "AI 玩法与叙事系统",
      "desc": "把模型能力转化成玩家可感知的规则、反馈和不确定性。",
      "proof": "动态 Prompt / RAG / 多结局叙事"
    },
    {
      "code": "CAP–02",
      "title": "游戏机制与系统设计",
      "desc": "从核心循环、状态变量到内容结构，建立可以解释和验证的玩法系统。",
      "proof": "心理状态引擎 / 经济循环 / 数值框架"
    },
    {
      "code": "CAP–03",
      "title": "快速原型实现",
      "desc": "不让策划停留在文档中，用可运行原型验证体验与技术风险。",
      "proof": "Godot / GDScript / Python"
    },
    {
      "code": "CAP–04",
      "title": "AI 产品实验",
      "desc": "从真实问题出发，用最小范围验证 API、工作流和交互方案。",
      "proof": "工具原型 / API 容错 / 工作流设计"
    }
  ],
  "journey": [
    {
      "date": "2026 / NOW",
      "title": "进入工业化游戏生产",
      "label": "CURRENT",
      "text": "在腾讯互动担任 AI 游戏策划实习生，把个人原型经验迁移到真实团队协作。"
    },
    {
      "date": "2026 / 04",
      "title": "第一次职业验证",
      "label": "MILESTONE",
      "text": "持续重构作品与表达方式，获得腾讯子公司 AI 游戏策划实习 Offer。"
    },
    {
      "date": "2025 / 09",
      "title": "决定开始制作游戏",
      "label": "PIVOT",
      "text": "开始自学 Godot 引擎并制作入门原型，游戏制作由兴趣转化为持续实践。"
    },
    {
      "date": "2024",
      "title": "从 AI 专业走向游戏",
      "label": "ORIGIN",
      "text": "在人工智能学习之外，通过竞赛、工具实验和游戏项目寻找更强的创造出口。"
    }
  ],
  "footprints": {
    "exploredCountry": "China",
    "provinces": {
      "浙江省": {
        "status": "EXPLORED",
        "title": "浙江 · 当前生活与成长坐标",
        "summary": "学习与职业实践目前主要发生在浙江。温州对应大学阶段，杭州对应进入 AI 游戏策划真实生产环境的职业阶段。"
      },
      "北京市": {
        "status": "EXPLORED",
        "title": "北京",
        "summary": ""
      },
      "福建省": {
        "status": "EXPLORED",
        "title": "福建 · 常年生活之地",
        "summary": "常年生活之地，感觉非常不错"
      },
      "上海市": {
        "status": "EXPLORED",
        "title": "上海",
        "summary": ""
      },
      "江西省": {
        "status": "EXPLORED",
        "title": "江西",
        "summary": ""
      },
      "四川省": {
        "status": "EXPLORED",
        "title": "四川",
        "summary": ""
      },
      "安徽省": {
        "status": "EXPLORED",
        "title": "安徽",
        "summary": ""
      }
    },
    "records": [
      {
        "country": "China",
        "countryLabel": "中国",
        "name": "Silver.Z",
        "place": "杭州",
        "date": "经常",
        "text": "陆陆续续来了这里很多次，挺好",
        "image": {
          "src": "assets/uploads/1785580424539-ca449a-asset.jpg"
        },
        "province": "浙江省"
      },
      {
        "country": "China",
        "countryLabel": "中国",
        "name": "Silver.Z",
        "place": "温州",
        "date": "大学阶段",
        "text": "在温州读书，也在温州看山水",
        "province": "浙江省",
        "image": {
          "src": "assets/uploads/1785584085168-5b9d59-_20260801193322_77_16.jpg"
        }
      },
      {
        "name": "Silver.Z",
        "country": "South Korea",
        "countryLabel": "韩国",
        "province": "",
        "place": "济州岛",
        "date": "2025.11.20",
        "text": "冬天的海——关于济州岛的那些事",
        "image": {
          "src": "assets/uploads/1785583538998-160f2e-_2026-08-01_192518_090.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "北京市",
        "place": "北京",
        "date": "2025.11.07",
        "text": "挚友一纸邀约，恰撞北京秋意漫城",
        "image": {
          "src": "assets/uploads/1785584343213-7d61e0-_2026-08-01_193812_471.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "福建省",
        "place": "福州",
        "date": "2026.04.25",
        "text": "随便逛逛",
        "image": {
          "src": "assets/uploads/1785584568181-b05d38-_2026-08-01_194215_471.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "福建省",
        "place": "漳州",
        "date": "经常",
        "text": "惬意的城市",
        "image": {
          "src": "assets/uploads/1785584737039-fa1a89-_2026-08-01_194526_295.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "福建省",
        "place": "厦门",
        "date": "2023.07",
        "text": "观海，但没有照片记录，以后补",
        "image": {
          "src": "",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "福建省",
        "place": "莆田 · 湄洲岛",
        "date": "2023.08.11",
        "text": "那年高考后的浅玩",
        "image": {
          "src": "assets/uploads/1785585134387-a576b5-_2026-08-01_195128_216.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "上海市",
        "place": "上海",
        "date": "2024.05.01",
        "text": "随便逛逛",
        "image": {
          "src": "assets/uploads/1785585404329-6e6919-_2026-08-01_195524_595.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "江西省",
        "place": "萍乡 · 武功山",
        "date": "2024.09.16",
        "text": "标记了一处地点，成功夜爬登顶",
        "image": {
          "src": "assets/uploads/1785585562984-6ef496-_2026-08-01_195832_888.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "四川省",
        "place": "成都",
        "date": "2025.02.10",
        "text": "去民航实习，第一次坐飞机",
        "image": {
          "src": "assets/uploads/1785585761195-834323-_2026-08-01_200212_218.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "浙江省",
        "place": "衢州",
        "date": "经常",
        "text": "老家，常回老家看看",
        "image": {
          "src": "assets/uploads/1785585880501-7f5b5c-_2026-08-01_200432_003.jpg",
          "caption": ""
        }
      },
      {
        "name": "Silver.Z",
        "country": "China",
        "countryLabel": "中国",
        "province": "安徽省",
        "place": "颍上",
        "date": "很久远的时候了",
        "text": "老妈的老家，外公外婆那，可惜没留照片，今天过年可以去拍",
        "image": {
          "src": "",
          "caption": ""
        }
      }
    ]
  },
  "versions": [
    {
      "version": "v21.4",
      "date": "2026.07",
      "title": "职业迁移进行中",
      "changes": [
        [
          "ADD",
          "进入 AI 游戏策划的真实生产环境"
        ],
        [
          "ADD",
          "建立 Silver OS 产品方向"
        ],
        [
          "FIX",
          "减少同时推进的支线项目"
        ],
        [
          "NEXT",
          "完成一个可公开体验的 AI 产品"
        ]
      ]
    },
    {
      "version": "v21.1",
      "date": "2026.04",
      "title": "作品集重构版本",
      "changes": [
        [
          "ADD",
          "获得腾讯互动实习 Offer"
        ],
        [
          "ADD",
          "完成 0号审讯室核心循环"
        ],
        [
          "LEARN",
          "外部反馈比封闭自评更有效"
        ]
      ]
    },
    {
      "version": "v20.6",
      "date": "2025.09",
      "title": "游戏制作起点",
      "changes": [
        [
          "ADD",
          "决定开始学习游戏制作"
        ],
        [
          "ADD",
          "开始自学 Godot 引擎"
        ],
        [
          "LEARN",
          "完成第一批游戏制作入门练习"
        ]
      ]
    }
  ],
  "socials": [
    {
      "label": "GitHub",
      "href": "https://github.com/Sat-Y?tab=repositories"
    },
    {
      "label": "Douyin",
      "href": "https://www.douyin.com/user/MS4wLjABAAAAm1NLHxmXfGA4qVcc-2YIAgt3stWfl_zaNozQ13hUR-uq-dHHYggP68kIaGRLPfg8"
    }
  ]
};
