/* Generated by Silver Content Studio. Verified trading records only. */
window.SILVER_TRADING = {
  "capital": {
    "initial": 10000,
    "current": 11721.49,
    "snapshots": [
      {
        "date": "2026-08-17",
        "capital": 11435,
        "pnl": null,
        "pnlPercent": null,
        "journalId": "",
        "note": ""
      },
      {
        "date": "2026-08-18",
        "capital": 11721.49,
        "pnl": null,
        "pnlPercent": null,
        "journalId": "",
        "note": ""
      },
      {
        "date": "2026-08-01",
        "capital": 10000,
        "pnl": null,
        "pnlPercent": null,
        "journalId": "",
        "note": ""
      }
    ],
    "monthly": [],
    "milestones": [
      {
        "amount": 20000,
        "label": "START",
        "status": "waiting"
      },
      {
        "amount": 50000,
        "label": "+10%",
        "status": "waiting"
      },
      {
        "amount": 100000,
        "label": "TARGET",
        "status": "waiting"
      },
      {
        "amount": 1000000,
        "label": "NEXT",
        "status": "waiting"
      }
    ]
  },
  "strategy": {
    "version": "STS / EVOLVING SYSTEM",
    "status": "IN DEVELOPMENT",
    "style": "热门题材 + 有辨识度个股 + 合理位置 + 分歧 / 回踩介入",
    "principle": "不孤立交易一只股票。个股必须放到市场、板块与个股的环境中理解。",
    "flow": [
      "Market",
      "Sector",
      "Stock",
      "Position",
      "Volume & Price",
      "Support",
      "Divergence / Consensus",
      "Plan",
      "Execution",
      "Review"
    ],
    "setups": [
      {
        "id": "SETUP 01",
        "title": "Strong Sector Pullback",
        "cn": "强势板块回踩",
        "summary": "板块强势，个股具备辨识度；等待分歧回踩关键位置并确认承接后介入。",
        "checks": [
          "板块仍然强势",
          "个股地位清晰",
          "关键位置出现承接"
        ]
      },
      {
        "id": "SETUP 02",
        "title": "Divergence Buy",
        "cn": "分歧低吸",
        "summary": "分歧不是买点。真正需要判断的是分歧之后有没有承接。",
        "checks": [
          "龙头保持稳定",
          "量价与支撑有效",
          "板块存在回流"
        ]
      },
      {
        "id": "SETUP 03",
        "title": "Breakout Confirmation",
        "cn": "突破确认",
        "summary": "突破本身不能成为买入理由，必须同时验证板块、成交量、地位与市场情绪。",
        "checks": [
          "突破获得量能确认",
          "市场情绪允许",
          "回踩没有破坏结构"
        ]
      }
    ],
    "planScenarios": [
      "HIGH OPEN",
      "FLAT OPEN",
      "LOW OPEN"
    ],
    "planFields": [
      "Support",
      "Resistance",
      "Entry",
      "Stop Loss",
      "Target",
      "Invalid Condition"
    ]
  },
  "journals": [
    {
      "id": "journal-2026-08-18",
      "date": "2026-08-18",
      "title": "正式的交易记录第一天",
      "context": "重点观察板块：\n1. PCB板块继续保持强势，但进入主升后的第一次大分歧阶段。\n2. 光纤光缆板块趋势健康，EMA继续发散，尚未出现明显见顶信号。\n3. 玻璃基板板块整体走强，沃格作为龙头没有继续领涨，京东方尾盘开始回流，彩虹股份尾盘重新封板，说明资金开始由龙头向板块扩散，而非单一龙头行情。\n\n市场情绪：\n虽然盘中分歧明显增加",
      "conversations": [
        {
          "role": "silver",
          "content": "① 上午讨论了百花医药是否应该止损。\n最初执行固定价格止损（13.60），盘中最低13.42，最终13.50卖出。\n随后发现百花下午重新反弹至13.80，但收盘重新回到13.50附近。\n\n最终讨论结论：\n止损方向没有错误，但STS需要升级：\n由\"价格止损\"升级为\n\"价格 + 时间 + 结构\"止损。\n\n━━━━━━━━━━━━━━\n\n② 彩虹股份盘中多次炸板。\n观察到：\n10.55形成第一次支撑\n↓\n10.60形成第二次支撑\n↓\n10.65形成第三次支撑\n说明资金重心不断提高。\n\n━━━━━━━━━━━━━━"
        }
      ],
      "decision": "1、百花医药执行止损，接受50元亏损。\n2、彩虹股份在10.60右侧确认加仓200股。\n目前持仓：彩虹300股，成本9.26，新增仓位T+1。\n3、方正科技继续持有400股。\n4、杭电股份继续持有100股。",
      "execution": "① 百花医药\n13.50卖出100股，亏损约50元。\n② 彩虹股份\n上午10.60买入200股。\n盘中经历两次炸板，但均快速回封。\n收盘涨停10.80。\n③ 方正科技\n盘中最高13.50。\n未按计划减仓。\n最终继续持有。\n④ 杭电股份\n盘中一度跌破29.50附近。\n最终没有止损。\n下午重新回升。",
      "result": "① 百花：\n收盘13.50。证明止损价格合理，但盘中波动较大。\n② 彩虹：\n成功涨停。\n全天高换手，多次炸板后尾盘封死。\n属于强势换手板。\n③ 方正：\n冲高回落。\n最终收13.14。\n保持盈利。\n④ 杭电：\n正常调整。\n收盘29.50。\n趋势没有被破坏。",
      "review": "今天最大的优点：\n① 百花虽然卖飞了一部分反弹，但严格执行纪律，没有因为情绪取消止损。\n② 彩虹加仓属于右侧确认，而不是左侧抄底。\n③ 杭电没有因为盘中波动而情绪化卖出。\n\n今天最大的不足：\n① 方正13.50附近没有按计划兑现部分利润。\n原因：高估了PCB继续加速上涨的概率。\n以后：如果放量冲高失败，需要主动降低预期。\n\n今天最大的认知提升：\n开始从\"分析个股\"升级到\"分析板块资金流向\"。\n观察到：\n沃格（龙头）\n↓\n京东方（中军）\n↓\n彩虹（弹性）\n\n资金开始扩散，而不是龙头独涨。",
      "lesson": "今天不是一次简单的盈利交易。\n而是STS正式从\"个股交易系统\"升级为\"板块驱动交易系统\"的第一天。\n以后交易，将优先分析板块，再决定个股操作。"
    }
  ]
};
