const http = require("http");
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const crypto = require("crypto");
const { spawn } = require("child_process");

const HOST = "127.0.0.1";
const PORT = Number(process.env.SILVER_STUDIO_PORT || 4178);
const ROOT = path.resolve(__dirname, "..");
const PUBLIC = path.join(__dirname, "public");
const DATA_DIR = path.join(__dirname, "data");
const BACKUP_DIR = path.join(DATA_DIR, "backups");
const STAGED_UPLOAD_DIR = path.join(DATA_DIR, "uploads");
const STUDIO_DATA = path.join(DATA_DIR, "studio-data.json");
const CONTENT_FILE = path.join(ROOT, "content.js");
const TRADING_FILE = path.join(ROOT, "trading-data.js");
const UPLOAD_DIR = path.join(ROOT, "assets", "uploads");

for (const dir of [DATA_DIR, BACKUP_DIR, STAGED_UPLOAD_DIR, UPLOAD_DIR]) fs.mkdirSync(dir, { recursive: true });

function readContentData() {
  const source = fs.readFileSync(CONTENT_FILE, "utf8");
  const context = { window: {} };
  vm.runInNewContext(source, context, { filename: CONTENT_FILE });
  return migrateData(JSON.parse(JSON.stringify(context.window.SILVER_DATA)));
}

function readTradingData() {
  if (!fs.existsSync(TRADING_FILE)) return { capital: { initial: null, current: null, snapshots: [], monthly: [], milestones: [] }, strategy: { flow: [], setups: [], planScenarios: [], planFields: [] }, journals: [] };
  const source = fs.readFileSync(TRADING_FILE, "utf8");
  const context = { window: {} };
  vm.runInNewContext(source, context, { filename: TRADING_FILE });
  return JSON.parse(JSON.stringify(context.window.SILVER_TRADING || {}));
}

function migrateData(data) {
  data.trading ||= readTradingData();
  data.trading.capital ||= { initial: null, current: null, snapshots: [], monthly: [], milestones: [] };
  data.trading.capital.snapshots ||= [];
  data.trading.capital.milestones ||= [];
  data.trading.strategy ||= { flow: [], setups: [], planScenarios: [], planFields: [] };
  data.trading.strategy.flow ||= [];
  data.trading.strategy.setups ||= [];
  data.trading.strategy.planScenarios ||= [];
  data.trading.strategy.planFields ||= [];
  data.trading.journals ||= [];
  data.footprints ||= {};
  if (!Array.isArray(data.footprints.records)) {
    data.footprints.records = (data.footprints.countryFeed || []).map(post => ({ country: "China", countryLabel: "中国", ...post }));
  }
  const feed = data.footprints.records;
  const provinces = data?.footprints?.provinces || {};
  for (const post of feed) {
    if (!post.country) post.country = post.province ? "China" : "";
    if (post.country === "China" && !post.countryLabel) post.countryLabel = "中国";
    if (post.province) continue;
    const match = Object.entries(provinces).find(([, record]) => (record.locations || []).some(location => location[0] === post.place));
    if (match) post.province = match[0];
  }
  delete data.footprints.countryFeed;
  Object.values(provinces).forEach(record => { delete record.locations; });
  return data;
}

function readStudioData() {
  if (!fs.existsSync(STUDIO_DATA)) {
    const initial = readContentData();
    fs.writeFileSync(STUDIO_DATA, JSON.stringify(initial, null, 2), "utf8");
    return initial;
  }
  return migrateData(JSON.parse(fs.readFileSync(STUDIO_DATA, "utf8")));
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

function backupData(label, data) {
  const file = path.join(BACKUP_DIR, `${timestamp()}-${label}.json`);
  fs.writeFileSync(file, JSON.stringify(data, null, 2), "utf8");
  return path.basename(file);
}

function filterPublic(value) {
  if (Array.isArray(value)) {
    return value.filter(item => !item || typeof item !== "object" || !item._visibility || item._visibility === "published")
      .map(filterPublic);
  }
  if (!value || typeof value !== "object") return value;
  const output = {};
  for (const [key, child] of Object.entries(value)) {
    if (key.startsWith("_")) continue;
    if (child && !Array.isArray(child) && typeof child === "object" && child._visibility && child._visibility !== "published") continue;
    output[key] = filterPublic(child);
  }
  return output;
}

function serializeContent(data) {
  const { trading, ...siteData } = data;
  return `/* Generated by Silver Content Studio. Public content only. */\nwindow.SILVER_DATA = ${JSON.stringify(filterPublic(siteData), null, 2)};\n`;
}

function serializeTrading(data) {
  return `/* Generated by Silver Content Studio. Verified trading records only. */\nwindow.SILVER_TRADING = ${JSON.stringify(filterPublic(data.trading || {}), null, 2)};\n`;
}

function collectAssetPaths(value, found = new Set()) {
  if (Array.isArray(value)) value.forEach(item => collectAssetPaths(item, found));
  else if (value && typeof value === "object") Object.values(value).forEach(item => collectAssetPaths(item, found));
  else if (typeof value === "string" && value.startsWith("assets/uploads/")) found.add(path.basename(value));
  return found;
}

function json(res, status, payload) {
  res.writeHead(status, { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" });
  res.end(JSON.stringify(payload));
}

function collectJson(req, maxBytes = 100 * 1024 * 1024) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    req.on("data", chunk => {
      size += chunk.length;
      if (size > maxBytes) {
        reject(new Error("请求内容过大"));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      try { resolve(JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}")); }
      catch { reject(new Error("JSON 格式无效")); }
    });
    req.on("error", reject);
  });
}

const mime = {
  ".html": "text/html; charset=utf-8", ".css": "text/css; charset=utf-8", ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg", ".webp": "image/webp", ".gif": "image/gif", ".mp4": "video/mp4", ".webm": "video/webm"
};

function sendFile(res, file) {
  if (!fs.existsSync(file) || !fs.statSync(file).isFile()) return json(res, 404, { error: "文件不存在" });
  res.writeHead(200, { "Content-Type": mime[path.extname(file).toLowerCase()] || "application/octet-stream", "Cache-Control": "no-store" });
  fs.createReadStream(file).pipe(res);
}

function safeResolve(base, relative) {
  const file = path.resolve(base, relative);
  return file === base || file.startsWith(base + path.sep) ? file : null;
}

async function handleApi(req, res, url) {
  if (req.method === "GET" && url.pathname === "/api/data") return json(res, 200, { data: readStudioData() });
  if (req.method === "GET" && url.pathname === "/api/map-options") {
    const source = fs.readFileSync(path.join(ROOT, "assets", "maps", "world-countries.js"), "utf8");
    const context = { window: {} };
    vm.runInNewContext(source, context);
    const countries = (context.window.SILVER_WORLD_MAP?.features || []).map(feature => feature.properties?.name).filter(Boolean).sort();
    return json(res, 200, { countries });
  }
  if (req.method === "GET" && url.pathname === "/api/status") {
    const stat = fs.statSync(CONTENT_FILE);
    const backups = fs.readdirSync(BACKUP_DIR).filter(name => name.endsWith(".json")).sort().reverse().slice(0, 8);
    return json(res, 200, { root: ROOT, backupDirectory: BACKUP_DIR, contentUpdatedAt: stat.mtime.toISOString(), backups });
  }
  if (req.method === "POST" && url.pathname === "/api/save") {
    const body = await collectJson(req);
    if (!body.data || typeof body.data !== "object") throw new Error("缺少有效内容数据");
    const current = fs.existsSync(STUDIO_DATA) ? JSON.parse(fs.readFileSync(STUDIO_DATA, "utf8")) : {};
    backupData("autosave", current);
    fs.writeFileSync(STUDIO_DATA, JSON.stringify(body.data, null, 2), "utf8");
    return json(res, 200, { ok: true, savedAt: new Date().toISOString() });
  }
  if (req.method === "POST" && url.pathname === "/api/export") {
    const data = readStudioData();
    const publicData = filterPublic(data);
    backupData("before-export", readContentData());
    fs.writeFileSync(CONTENT_FILE, serializeContent(data), "utf8");
    fs.writeFileSync(TRADING_FILE, serializeTrading(data), "utf8");
    for (const filename of collectAssetPaths(publicData)) {
      const staged = path.join(STAGED_UPLOAD_DIR, filename);
      if (fs.existsSync(staged)) fs.copyFileSync(staged, path.join(UPLOAD_DIR, filename));
    }
    return json(res, 200, { ok: true, exportedAt: new Date().toISOString(), targets: [CONTENT_FILE, TRADING_FILE] });
  }
  if (req.method === "POST" && url.pathname === "/api/restore") {
    const body = await collectJson(req);
    const filename = path.basename(String(body.filename || ""));
    if (!filename.endsWith(".json")) throw new Error("备份文件无效");
    const source = path.join(BACKUP_DIR, filename);
    if (!fs.existsSync(source)) throw new Error("找不到这个备份");
    const restored = JSON.parse(fs.readFileSync(source, "utf8"));
    backupData("before-restore", readStudioData());
    fs.writeFileSync(STUDIO_DATA, JSON.stringify(restored, null, 2), "utf8");
    return json(res, 200, { ok: true, data: restored, restoredFrom: filename });
  }
  if (req.method === "POST" && url.pathname === "/api/upload") {
    const body = await collectJson(req);
    const match = String(body.data || "").match(/^data:([^;]+);base64,(.+)$/);
    if (!match) throw new Error("上传数据无效");
    const originalExt = path.extname(String(body.name || "")).toLowerCase();
    const allowed = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".mp4", ".webm"]);
    if (!allowed.has(originalExt)) throw new Error("仅支持 PNG、JPG、WEBP、GIF、MP4 和 WEBM");
    const stem = path.basename(String(body.name || "asset"), originalExt).replace(/[^a-zA-Z0-9_-]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "asset";
    const filename = `${Date.now()}-${crypto.randomBytes(3).toString("hex")}-${stem}${originalExt === ".jpeg" ? ".jpg" : originalExt}`;
    fs.writeFileSync(path.join(STAGED_UPLOAD_DIR, filename), Buffer.from(match[2], "base64"));
    return json(res, 200, { ok: true, path: `assets/uploads/${filename}` });
  }
  return json(res, 404, { error: "接口不存在" });
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${HOST}:${PORT}`);
  try {
    if (url.pathname === "/favicon.ico") { res.writeHead(204); return res.end(); }
    if (url.pathname.startsWith("/api/")) return await handleApi(req, res, url);
    if (url.pathname === "/site/content.js") {
      res.writeHead(200, { "Content-Type": "text/javascript; charset=utf-8", "Cache-Control": "no-store" });
      const { trading, ...siteData } = readStudioData();
      return res.end(`window.SILVER_DATA = ${JSON.stringify(siteData)};`);
    }
    if (url.pathname === "/site/trading-data.js") {
      res.writeHead(200, { "Content-Type": "text/javascript; charset=utf-8", "Cache-Control": "no-store" });
      return res.end(`window.SILVER_TRADING = ${JSON.stringify(readStudioData().trading || {})};`);
    }
    if (url.pathname.startsWith("/site/assets/uploads/")) {
      const filename = path.basename(decodeURIComponent(url.pathname));
      const staged = path.join(STAGED_UPLOAD_DIR, filename);
      if (fs.existsSync(staged)) return sendFile(res, staged);
    }
    if (url.pathname.startsWith("/site/")) {
      const relative = decodeURIComponent(url.pathname.slice(6)) || "index.html";
      const file = safeResolve(ROOT, relative);
      return file ? sendFile(res, file) : json(res, 403, { error: "路径不允许" });
    }
    const relative = url.pathname === "/" ? "index.html" : decodeURIComponent(url.pathname.slice(1));
    const file = safeResolve(PUBLIC, relative);
    return file ? sendFile(res, file) : json(res, 403, { error: "路径不允许" });
  } catch (error) {
    console.error(error);
    json(res, 500, { error: error.message || "本地服务发生错误" });
  }
});

server.listen(PORT, HOST, () => {
  const studioUrl = `http://${HOST}:${PORT}`;
  const siteUrl = `${studioUrl}/site/index.html`;
  console.log(`Silver OS Frontend: ${siteUrl}`);
  console.log(`Silver Content Studio: ${studioUrl}`);
  console.log(`Website root: ${ROOT}`);
  if (process.platform === "win32" && process.env.SILVER_STUDIO_NO_OPEN !== "1") {
    spawn("cmd", ["/c", "start", "", siteUrl], { windowsHide: true, detached: true, stdio: "ignore" }).unref();
    spawn("cmd", ["/c", "start", "", studioUrl], { windowsHide: true, detached: true, stdio: "ignore" }).unref();
  }
});

server.on("error", error => {
  if (error.code === "EADDRINUSE") {
    console.error(`端口 ${PORT} 已被占用。Silver OS 可能已经启动，请打开 http://${HOST}:${PORT}`);
    process.exitCode = 1;
    return;
  }
  throw error;
});
